name: validate

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  renovate-config-validator:
    runs-on: [self-hosted, linux, arcana-prod]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Validate preset JSON files
        run: npx --yes --package renovate -- renovate-config-validator default.json nestjs.json react.json
